spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  main:
    allow-circular-references: true


# =================================
# Imgur
# =================================
imgur:
  client:
    accessToken: <AccessToken>
    accessTokenUrl: https://api.imgur.com/oauth2/token
    authorizeUrl: https://api.imgur.com/oauth2/authorize
    clientId: <ClientId>
    clientSecret: 86da8fc7f0ab6b9297b760f16623fd2ff6be752d
    uploadUrl: <SecretId>


